### ISSUE TITLE
installDebugHook is causing a segmentation fault (core dumped)

### ISSUE THREAD

**Issue by joe9** [ekmett/quine#10]
Hello,

Thanks for sharing quine and gl.

The call to gl_KHR_debug of installDebugHook is causing a core dump when used with OpenGL 3.3. I presume you do not expect installDebugHook to be used outside the scope of this project. If you do, just want to bring this to your attention.

Thanks

**Comment by ekmett** [comment]
Do you have an active OpenGL context?

**Comment by joe9** [comment]
Your observation is spot-on.

I did not have an OpenGL context? I was doing the installDebugHook before this call:     GLFW.makeContextCurrent window

Thanks again.

**Comment by ekmett** [comment]
Nothing involving OpenGL will work until you have a context to run it on. Something like glew, glfw, direct window calls, or sdl sets up the context for you. Then `gl` has functions it can call. We could bake all of this into the API by making you pass around a gigantic table of functions everywhere, but the API becomes a lot less usable that way. (On the other hand, then it could work with multiple GL contexts, so there is something to be said for that design as well.)
