### ISSUE TITLE
Cartoon shader causes ShaderException

### ISSUE THREAD

**Issue by jaspertron** [ekmett/quine#6]
If I run `toy` or `toy -F shaders/examples/cartoon.frag`, it crashes and says:

```
Monitoring enabled at http://localhost:5616/
ShaderException {shaderExceptionFileName = "shaders/examples/cartoon.frag", shaderExceptionLog = "/shaders/simtime.h(7) : error C1002: the name \"time\" is already defined at /shaders/simtime.h(7)\n"}
```

It only works if I remove [this line](https://github.com/ekmett/quine/blob/a04bebddf239e3a0177a8aa8b049537c83f9de5c/shaders/examples/cartoon.frag#L8).

All the other shaders work without modification.

**Comment by ekmett** [comment]
Fixed.
