### ISSUE TITLE
Template Haskell, Windows & SDL2

### ISSUE THREAD

**Issue by Twinside** [ekmett/quine#7]
Due to a [deep bug](https://ghc.haskell.org/trac/ghc/ticket/3242), template Haskell doesn't works on windows with sdl2 dynamic loading, it panics somehow. As TemplateHaskell seems mainly used to derive lenses for data structure, would you be interested by a pull request implementing by hand these lenses in order to make quine compile on windows?

**Comment by ekmett** [comment]
It sounds like this is fixed with the new linker in GHC 8.
